steps:
- name: node
  entrypoint: yarn
  args: ['install']
- name: node
  entrypoint: yarn
- name: node
  entrypoint: yarn
  args: ['run', 'build']
  env: [NODE_OPTIONS=--openssl-legacy-provider]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  timeout: '1600s'